In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
doc_mapping_path = '/content/drive/MyDrive/KLTN_Project/Datasets/unique_doc_mapping.csv'

In [4]:
doc_df = pd.read_csv(doc_mapping_path)
doc_df.head()

   doc_id                                           document
0       0  (Chinhphu.vn) - Đây là mong muốn, gửi gắm của ...
1       1  Ngày 24/3, Cơ quan Cảnh sát điều tra Công an t...
2       2  (PLO)- Theo Tổng Công ty Cấp nước Sài Gòn (SAW...
3       3  Với khoảng 200 thành viên, UEF Warm Hugs Club ...
4       4  Đi qua 2 năm dịch bệnh đầy thử thách, nhưng ch...

In [5]:
ids_to_lookup = ["44", "2764", "1456"]
filtered_df = doc_df[doc_df['doc_id'].astype(str).isin(ids_to_lookup)]
display(filtered_df)

      doc_id                                           document
44        44  (Chinhphu.vn) - Ngày 19/8, hơn 15.000 người dâ...
1456    1456  Nhật Bản là nước rất nghèo nàn về tài nguyên n...
2764    2764  Giảm phát là khi giá hàng hóa, dịch vụ liên tụ...